### ===================================================== ###
#default
spring:
  profiles.active: local

---
spring:
  profiles: local

serverPort: 7070
mongodbUri: localhost:27017

---
### common
server:
  port: ${serverPort}

# mongo db
mongo:
  uri: mongodb://${mongodbUri}/

spring.main.allow-bean-definition-overriding: true

# log
info: true
spring.output.ansi.enabled: ALWAYS
logging:
  level:
    root: INFO
    org.springframework.boot.autoconfigure.logging: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p - %logger{39} : %m%n"
    # original    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(-){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
